# Generated by Django 3.2.4 on 2021-06-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='categorie',
        ),
    ]
