# Generated by Django 3.2.4 on 2021-06-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_formation_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='categ',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='formation',
            name='titer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='etat',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
