# Generated by Django 3.2.4 on 2021-06-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210608_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
