# Generated by Django 3.2.4 on 2021-06-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_formation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='logo',
            field=models.ImageField(null=True, upload_to='user/static/images/'),
        ),
    ]
